apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: simple.tanzu.vmware.com
  namespace: default
spec:
  buildpacks:
    builder: tanzu-build-public.packages.broadcom.com/builders/builder-jammy-full
  postBuildSteps: []
  registry: "harbor.tanzu.rocks/apps/surfersapi"
  runtimes:
    - name: plain
      steps:
        - namedTask: tanzu-kubernetes-deployment
    - name: image
      steps:
        - namedTask: tanzu-container-image