apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: surfersapi
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: surferslookout
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/api/v1/api-docs"
      owner: group:surfers-crew
      system: surferslookout
      description: "Surferslookout forecast api"
  source:
    git:
      url: https://github.com/davlloyd/surfers-api
      ref:
        branch: main
