apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: surfersapi
spec:
  acceptedServiceBindings:
  - name: db
    types:
    - mysql
  build:
    buildpacks: {}
    path: ../..
  ports:
  - name: main
    port: 8080
